/**
 * Program IDL in camelCase format in order to be used in JS/TS.
 *
 * Note that this is only a type helper and is not the actual IDL. The original
 * IDL can be found at `target/idl/dive_game.json`.
 * 
 * AUTO-GENERATED - DO NOT EDIT MANUALLY
 * Generated by scripts/sync-idl.sh
 */

import type { Program } from '@coral-xyz/anchor';
import type { PublicKey } from '@solana/web3.js';

export type DiveGame = {
  "address": "2hMffkY1dCRo548Kj152LNyPomQAiFhw7dVAsgNbZ7F2",
  "metadata": {
    "name": "dive_game",
    "version": "0.1.0",
    "spec": "0.1.0",
    "description": "Dive game smart contract for Solana"
  },
  "instructions": [
    {
      "name": "cash_out",
      "discriminator": [
        1,
        110,
        57,
        58,
        159,
        157,
        243,
        192
      ],
      "accounts": [
        {
          "name": "user",
          "writable": true,
          "signer": true,
          "relations": [
            "session"
          ]
        },
        {
          "name": "session",
          "writable": true
        },
        {
          "name": "house_vault",
          "writable": true,
          "relations": [
            "session"
          ]
        }
      ],
      "args": []
    },
    {
      "name": "clean_expired_session",
      "discriminator": [
        198,
        119,
        17,
        15,
        128,
        185,
        80,
        231
      ],
      "accounts": [
        {
          "name": "crank",
          "docs": [
            "The crank/keeper calling this instruction",
            "Receives the rent as incentive"
          ],
          "writable": true,
          "signer": true
        },
        {
          "name": "house_vault",
          "docs": [
            "The house vault to release funds to"
          ],
          "writable": true,
          "relations": [
            "session"
          ]
        },
        {
          "name": "session",
          "docs": [
            "The expired session to clean up",
            "Account closes automatically and rent goes to crank"
          ],
          "writable": true
        }
      ],
      "args": []
    },
    {
      "name": "init_config",
      "discriminator": [
        23,
        235,
        115,
        232,
        168,
        96,
        1,
        231
      ],
      "accounts": [
        {
          "name": "admin",
          "writable": true,
          "signer": true
        },
        {
          "name": "config",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  103,
                  97,
                  109,
                  101,
                  95,
                  99,
                  111,
                  110,
                  102,
                  105,
                  103
                ]
              }
            ]
          }
        },
        {
          "name": "system_program",
          "address": "11111111111111111111111111111111"
        }
      ],
      "args": [
        {
          "name": "params",
          "type": {
            "defined": {
              "name": "GameConfigParams"
            }
          }
        }
      ]
    },
    {
      "name": "init_house_vault",
      "discriminator": [
        82,
        247,
        65,
        25,
        166,
        239,
        30,
        112
      ],
      "accounts": [
        {
          "name": "house_authority",
          "writable": true,
          "signer": true
        },
        {
          "name": "house_vault",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  104,
                  111,
                  117,
                  115,
                  101,
                  95,
                  118,
                  97,
                  117,
                  108,
                  116
                ]
              },
              {
                "kind": "account",
                "path": "house_authority"
              }
            ]
          }
        },
        {
          "name": "system_program",
          "address": "11111111111111111111111111111111"
        }
      ],
      "args": [
        {
          "name": "locked",
          "type": "bool"
        }
      ]
    },
    {
      "name": "lose_session",
      "discriminator": [
        13,
        163,
        66,
        150,
        39,
        65,
        34,
        53
      ],
      "accounts": [
        {
          "name": "user",
          "writable": true,
          "signer": true,
          "relations": [
            "session"
          ]
        },
        {
          "name": "session",
          "writable": true
        },
        {
          "name": "house_vault",
          "writable": true,
          "relations": [
            "session"
          ]
        }
      ],
      "args": []
    },
    {
      "name": "play_round",
      "discriminator": [
        38,
        35,
        89,
        4,
        59,
        139,
        225,
        250
      ],
      "accounts": [
        {
          "name": "user",
          "writable": true,
          "signer": true,
          "relations": [
            "session"
          ]
        },
        {
          "name": "config",
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  103,
                  97,
                  109,
                  101,
                  95,
                  99,
                  111,
                  110,
                  102,
                  105,
                  103
                ]
              }
            ]
          }
        },
        {
          "name": "session",
          "writable": true
        },
        {
          "name": "house_vault",
          "writable": true,
          "relations": [
            "session"
          ]
        }
      ],
      "args": []
    },
    {
      "name": "reset_vault_reserved",
      "discriminator": [
        234,
        184,
        164,
        210,
        94,
        125,
        213,
        53
      ],
      "accounts": [
        {
          "name": "house_authority",
          "writable": true,
          "signer": true,
          "relations": [
            "house_vault"
          ]
        },
        {
          "name": "house_vault",
          "writable": true
        }
      ],
      "args": []
    },
    {
      "name": "start_session",
      "discriminator": [
        23,
        227,
        111,
        142,
        212,
        230,
        3,
        175
      ],
      "accounts": [
        {
          "name": "user",
          "writable": true,
          "signer": true
        },
        {
          "name": "config",
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  103,
                  97,
                  109,
                  101,
                  95,
                  99,
                  111,
                  110,
                  102,
                  105,
                  103
                ]
              }
            ]
          }
        },
        {
          "name": "house_vault",
          "writable": true
        },
        {
          "name": "house_authority",
          "relations": [
            "house_vault"
          ]
        },
        {
          "name": "session",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  115,
                  101,
                  115,
                  115,
                  105,
                  111,
                  110
                ]
              },
              {
                "kind": "account",
                "path": "user"
              },
              {
                "kind": "arg",
                "path": "session_index"
              }
            ]
          }
        },
        {
          "name": "system_program",
          "address": "11111111111111111111111111111111"
        }
      ],
      "args": [
        {
          "name": "session_index",
          "type": "u64"
        }
      ]
    },
    {
      "name": "toggle_house_lock",
      "discriminator": [
        170,
        63,
        166,
        115,
        196,
        253,
        239,
        115
      ],
      "accounts": [
        {
          "name": "house_authority",
          "writable": true,
          "signer": true,
          "relations": [
            "house_vault"
          ]
        },
        {
          "name": "house_vault",
          "writable": true
        }
      ],
      "args": []
    },
    {
      "name": "update_config",
      "discriminator": [
        29,
        158,
        252,
        191,
        10,
        83,
        219,
        99
      ],
      "accounts": [
        {
          "name": "admin",
          "writable": true,
          "signer": true,
          "relations": [
            "config"
          ]
        },
        {
          "name": "config",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  103,
                  97,
                  109,
                  101,
                  95,
                  99,
                  111,
                  110,
                  102,
                  105,
                  103
                ]
              }
            ]
          }
        }
      ],
      "args": [
        {
          "name": "params",
          "type": {
            "defined": {
              "name": "UpdateConfigParams"
            }
          }
        }
      ]
    },
    {
      "name": "withdraw_house",
      "discriminator": [
        226,
        236,
        222,
        156,
        198,
        230,
        70,
        147
      ],
      "accounts": [
        {
          "name": "house_authority",
          "writable": true,
          "signer": true,
          "relations": [
            "house_vault"
          ]
        },
        {
          "name": "house_vault",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  104,
                  111,
                  117,
                  115,
                  101,
                  95,
                  118,
                  97,
                  117,
                  108,
                  116
                ]
              },
              {
                "kind": "account",
                "path": "house_authority"
              }
            ]
          }
        }
      ],
      "args": [
        {
          "name": "amount",
          "type": "u64"
        }
      ]
    }
  ],
  "accounts": [
    {
      "name": "GameConfig",
      "discriminator": [
        45,
        146,
        146,
        33,
        170,
        69,
        96,
        133
      ]
    },
    {
      "name": "GameSession",
      "discriminator": [
        150,
        116,
        20,
        197,
        205,
        121,
        220,
        240
      ]
    },
    {
      "name": "HouseVault",
      "discriminator": [
        125,
        17,
        104,
        101,
        16,
        34,
        39,
        135
      ]
    }
  ],
  "events": [
    {
      "name": "InitializeHouseVaultEvent",
      "discriminator": [
        168,
        177,
        147,
        20,
        101,
        83,
        103,
        28
      ]
    },
    {
      "name": "RoundPlayedEvent",
      "discriminator": [
        254,
        181,
        20,
        116,
        246,
        74,
        159,
        248
      ]
    },
    {
      "name": "SessionCashedOutEvent",
      "discriminator": [
        195,
        76,
        152,
        45,
        138,
        65,
        41,
        62
      ]
    },
    {
      "name": "SessionCleanedEvent",
      "discriminator": [
        237,
        15,
        33,
        222,
        164,
        153,
        148,
        218
      ]
    },
    {
      "name": "SessionLostEvent",
      "discriminator": [
        195,
        211,
        168,
        54,
        137,
        90,
        214,
        163
      ]
    },
    {
      "name": "SessionStartedEvent",
      "discriminator": [
        94,
        226,
        93,
        23,
        167,
        17,
        206,
        191
      ]
    },
    {
      "name": "ToggleHouseLockEvent",
      "discriminator": [
        125,
        201,
        183,
        134,
        233,
        188,
        245,
        108
      ]
    }
  ],
  "errors": [
    {
      "code": 6000,
      "name": "HouseLocked",
      "msg": "House vault is locked"
    },
    {
      "code": 6001,
      "name": "InvalidSessionStatus",
      "msg": "Session is not active"
    },
    {
      "code": 6002,
      "name": "InvalidBetAmount",
      "msg": "Bet amount must be greater than zero"
    },
    {
      "code": 6003,
      "name": "RoundMismatch",
      "msg": "Round number mismatch"
    },
    {
      "code": 6004,
      "name": "TreasureInvalid",
      "msg": "Treasure amount invalid or exceeds max payout"
    },
    {
      "code": 6005,
      "name": "InsufficientVaultBalance",
      "msg": "Insufficient vault balance for payout"
    },
    {
      "code": 6006,
      "name": "Overflow",
      "msg": "Arithmetic overflow"
    },
    {
      "code": 6007,
      "name": "InsufficientTreasure",
      "msg": "Cannot cash out with treasure less than or equal to bet"
    },
    {
      "code": 6008,
      "name": "InvalidConfig",
      "msg": "Invalid game configuration"
    },
    {
      "code": 6009,
      "name": "MaxDivesReached",
      "msg": "Maximum number of dives reached"
    },
    {
      "code": 6010,
      "name": "InvalidSlotHash",
      "msg": "Could not retrieve valid slot hash from SlotHashes sysvar"
    },
    {
      "code": 6011,
      "name": "SessionNotExpired",
      "msg": "Session has not expired yet - cannot clean up"
    },
    {
      "code": 6012,
      "name": "VaultHasReservedFunds",
      "msg": "Cannot reset vault reserved when total_reserved > 0 - may have active sessions"
    },
    {
      "code": 6013,
      "name": "VaultCapacityExceeded",
      "msg": "Vault capacity exceeded - too many concurrent sessions would risk insolvency"
    }
  ],
  "types": [
    {
      "name": "GameConfig",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "admin",
            "type": "pubkey"
          },
          {
            "name": "base_survival_ppm",
            "type": "u32"
          },
          {
            "name": "decay_per_dive_ppm",
            "type": "u32"
          },
          {
            "name": "min_survival_ppm",
            "type": "u32"
          },
          {
            "name": "treasure_multiplier_num",
            "type": "u16"
          },
          {
            "name": "treasure_multiplier_den",
            "type": "u16"
          },
          {
            "name": "max_payout_multiplier",
            "type": "u16"
          },
          {
            "name": "max_dives",
            "type": "u16"
          },
          {
            "name": "fixed_bet",
            "type": "u64"
          },
          {
            "name": "bump",
            "type": "u8"
          }
        ]
      }
    },
    {
      "name": "GameConfigParams",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "base_survival_ppm",
            "type": {
              "option": "u32"
            }
          },
          {
            "name": "decay_per_dive_ppm",
            "type": {
              "option": "u32"
            }
          },
          {
            "name": "min_survival_ppm",
            "type": {
              "option": "u32"
            }
          },
          {
            "name": "treasure_multiplier_num",
            "type": {
              "option": "u16"
            }
          },
          {
            "name": "treasure_multiplier_den",
            "type": {
              "option": "u16"
            }
          },
          {
            "name": "max_payout_multiplier",
            "type": {
              "option": "u16"
            }
          },
          {
            "name": "max_dives",
            "type": {
              "option": "u16"
            }
          },
          {
            "name": "fixed_bet",
            "type": {
              "option": "u64"
            }
          }
        ]
      }
    },
    {
      "name": "GameSession",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "user",
            "type": "pubkey"
          },
          {
            "name": "house_vault",
            "type": "pubkey"
          },
          {
            "name": "status",
            "type": {
              "defined": {
                "name": "SessionStatus"
              }
            }
          },
          {
            "name": "bet_amount",
            "type": "u64"
          },
          {
            "name": "current_treasure",
            "type": "u64"
          },
          {
            "name": "max_payout",
            "type": "u64"
          },
          {
            "name": "dive_number",
            "type": "u16"
          },
          {
            "name": "bump",
            "type": "u8"
          },
          {
            "name": "last_active_slot",
            "docs": [
              "Phase 2: Activity tracking for timeout-based cleanup",
              "Slot number when session was last active",
              "Updated on: start_session, play_round (if survived), cash_out"
            ],
            "type": "u64"
          }
        ]
      }
    },
    {
      "name": "HouseVault",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "house_authority",
            "type": "pubkey"
          },
          {
            "name": "game_keeper",
            "type": "pubkey"
          },
          {
            "name": "locked",
            "type": "bool"
          },
          {
            "name": "total_reserved",
            "type": "u64"
          },
          {
            "name": "bump",
            "type": "u8"
          }
        ]
      }
    },
    {
      "name": "InitializeHouseVaultEvent",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "house_vault",
            "type": "pubkey"
          },
          {
            "name": "house_authority",
            "type": "pubkey"
          },
          {
            "name": "locked",
            "type": "bool"
          },
          {
            "name": "timestamp",
            "type": "i64"
          }
        ]
      }
    },
    {
      "name": "RoundPlayedEvent",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "session",
            "type": "pubkey"
          },
          {
            "name": "user",
            "type": "pubkey"
          },
          {
            "name": "dive_number",
            "type": "u16"
          },
          {
            "name": "current_treasure",
            "type": "u64"
          },
          {
            "name": "timestamp",
            "type": "i64"
          }
        ]
      }
    },
    {
      "name": "SessionCashedOutEvent",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "session",
            "type": "pubkey"
          },
          {
            "name": "user",
            "type": "pubkey"
          },
          {
            "name": "house_vault",
            "type": "pubkey"
          },
          {
            "name": "payout_amount",
            "type": "u64"
          },
          {
            "name": "final_dive_number",
            "type": "u16"
          },
          {
            "name": "timestamp",
            "type": "i64"
          }
        ]
      }
    },
    {
      "name": "SessionCleanedEvent",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "session",
            "type": "pubkey"
          },
          {
            "name": "user",
            "type": "pubkey"
          },
          {
            "name": "crank",
            "type": "pubkey"
          },
          {
            "name": "released_amount",
            "type": "u64"
          },
          {
            "name": "slots_inactive",
            "type": "u64"
          }
        ]
      }
    },
    {
      "name": "SessionLostEvent",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "session",
            "type": "pubkey"
          },
          {
            "name": "user",
            "type": "pubkey"
          },
          {
            "name": "house_vault",
            "type": "pubkey"
          },
          {
            "name": "bet_amount",
            "type": "u64"
          },
          {
            "name": "final_dive_number",
            "type": "u16"
          },
          {
            "name": "timestamp",
            "type": "i64"
          }
        ]
      }
    },
    {
      "name": "SessionStartedEvent",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "session",
            "type": "pubkey"
          },
          {
            "name": "user",
            "type": "pubkey"
          },
          {
            "name": "house_vault",
            "type": "pubkey"
          },
          {
            "name": "bet_amount",
            "type": "u64"
          },
          {
            "name": "max_payout",
            "type": "u64"
          },
          {
            "name": "timestamp",
            "type": "i64"
          }
        ]
      }
    },
    {
      "name": "SessionStatus",
      "type": {
        "kind": "enum",
        "variants": [
          {
            "name": "Active"
          },
          {
            "name": "Lost"
          },
          {
            "name": "CashedOut"
          }
        ]
      }
    },
    {
      "name": "ToggleHouseLockEvent",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "house_vault",
            "type": "pubkey"
          },
          {
            "name": "house_authority",
            "type": "pubkey"
          },
          {
            "name": "locked",
            "type": "bool"
          },
          {
            "name": "timestamp",
            "type": "i64"
          }
        ]
      }
    },
    {
      "name": "UpdateConfigParams",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "base_survival_ppm",
            "type": {
              "option": "u32"
            }
          },
          {
            "name": "decay_per_dive_ppm",
            "type": {
              "option": "u32"
            }
          },
          {
            "name": "min_survival_ppm",
            "type": {
              "option": "u32"
            }
          },
          {
            "name": "treasure_multiplier_num",
            "type": {
              "option": "u16"
            }
          },
          {
            "name": "treasure_multiplier_den",
            "type": {
              "option": "u16"
            }
          },
          {
            "name": "max_payout_multiplier",
            "type": {
              "option": "u16"
            }
          },
          {
            "name": "max_dives",
            "type": {
              "option": "u16"
            }
          },
          {
            "name": "fixed_bet",
            "type": {
              "option": "u64"
            }
          }
        ]
      }
    }
  ]
};

export const IDL: DiveGame = {
  "address": "2hMffkY1dCRo548Kj152LNyPomQAiFhw7dVAsgNbZ7F2",
  "metadata": {
    "name": "dive_game",
    "version": "0.1.0",
    "spec": "0.1.0",
    "description": "Dive game smart contract for Solana"
  },
  "instructions": [
    {
      "name": "cash_out",
      "discriminator": [
        1,
        110,
        57,
        58,
        159,
        157,
        243,
        192
      ],
      "accounts": [
        {
          "name": "user",
          "writable": true,
          "signer": true,
          "relations": [
            "session"
          ]
        },
        {
          "name": "session",
          "writable": true
        },
        {
          "name": "house_vault",
          "writable": true,
          "relations": [
            "session"
          ]
        }
      ],
      "args": []
    },
    {
      "name": "clean_expired_session",
      "discriminator": [
        198,
        119,
        17,
        15,
        128,
        185,
        80,
        231
      ],
      "accounts": [
        {
          "name": "crank",
          "docs": [
            "The crank/keeper calling this instruction",
            "Receives the rent as incentive"
          ],
          "writable": true,
          "signer": true
        },
        {
          "name": "house_vault",
          "docs": [
            "The house vault to release funds to"
          ],
          "writable": true,
          "relations": [
            "session"
          ]
        },
        {
          "name": "session",
          "docs": [
            "The expired session to clean up",
            "Account closes automatically and rent goes to crank"
          ],
          "writable": true
        }
      ],
      "args": []
    },
    {
      "name": "init_config",
      "discriminator": [
        23,
        235,
        115,
        232,
        168,
        96,
        1,
        231
      ],
      "accounts": [
        {
          "name": "admin",
          "writable": true,
          "signer": true
        },
        {
          "name": "config",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  103,
                  97,
                  109,
                  101,
                  95,
                  99,
                  111,
                  110,
                  102,
                  105,
                  103
                ]
              }
            ]
          }
        },
        {
          "name": "system_program",
          "address": "11111111111111111111111111111111"
        }
      ],
      "args": [
        {
          "name": "params",
          "type": {
            "defined": {
              "name": "GameConfigParams"
            }
          }
        }
      ]
    },
    {
      "name": "init_house_vault",
      "discriminator": [
        82,
        247,
        65,
        25,
        166,
        239,
        30,
        112
      ],
      "accounts": [
        {
          "name": "house_authority",
          "writable": true,
          "signer": true
        },
        {
          "name": "house_vault",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  104,
                  111,
                  117,
                  115,
                  101,
                  95,
                  118,
                  97,
                  117,
                  108,
                  116
                ]
              },
              {
                "kind": "account",
                "path": "house_authority"
              }
            ]
          }
        },
        {
          "name": "system_program",
          "address": "11111111111111111111111111111111"
        }
      ],
      "args": [
        {
          "name": "locked",
          "type": "bool"
        }
      ]
    },
    {
      "name": "lose_session",
      "discriminator": [
        13,
        163,
        66,
        150,
        39,
        65,
        34,
        53
      ],
      "accounts": [
        {
          "name": "user",
          "writable": true,
          "signer": true,
          "relations": [
            "session"
          ]
        },
        {
          "name": "session",
          "writable": true
        },
        {
          "name": "house_vault",
          "writable": true,
          "relations": [
            "session"
          ]
        }
      ],
      "args": []
    },
    {
      "name": "play_round",
      "discriminator": [
        38,
        35,
        89,
        4,
        59,
        139,
        225,
        250
      ],
      "accounts": [
        {
          "name": "user",
          "writable": true,
          "signer": true,
          "relations": [
            "session"
          ]
        },
        {
          "name": "config",
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  103,
                  97,
                  109,
                  101,
                  95,
                  99,
                  111,
                  110,
                  102,
                  105,
                  103
                ]
              }
            ]
          }
        },
        {
          "name": "session",
          "writable": true
        },
        {
          "name": "house_vault",
          "writable": true,
          "relations": [
            "session"
          ]
        }
      ],
      "args": []
    },
    {
      "name": "reset_vault_reserved",
      "discriminator": [
        234,
        184,
        164,
        210,
        94,
        125,
        213,
        53
      ],
      "accounts": [
        {
          "name": "house_authority",
          "writable": true,
          "signer": true,
          "relations": [
            "house_vault"
          ]
        },
        {
          "name": "house_vault",
          "writable": true
        }
      ],
      "args": []
    },
    {
      "name": "start_session",
      "discriminator": [
        23,
        227,
        111,
        142,
        212,
        230,
        3,
        175
      ],
      "accounts": [
        {
          "name": "user",
          "writable": true,
          "signer": true
        },
        {
          "name": "config",
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  103,
                  97,
                  109,
                  101,
                  95,
                  99,
                  111,
                  110,
                  102,
                  105,
                  103
                ]
              }
            ]
          }
        },
        {
          "name": "house_vault",
          "writable": true
        },
        {
          "name": "house_authority",
          "relations": [
            "house_vault"
          ]
        },
        {
          "name": "session",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  115,
                  101,
                  115,
                  115,
                  105,
                  111,
                  110
                ]
              },
              {
                "kind": "account",
                "path": "user"
              },
              {
                "kind": "arg",
                "path": "session_index"
              }
            ]
          }
        },
        {
          "name": "system_program",
          "address": "11111111111111111111111111111111"
        }
      ],
      "args": [
        {
          "name": "session_index",
          "type": "u64"
        }
      ]
    },
    {
      "name": "toggle_house_lock",
      "discriminator": [
        170,
        63,
        166,
        115,
        196,
        253,
        239,
        115
      ],
      "accounts": [
        {
          "name": "house_authority",
          "writable": true,
          "signer": true,
          "relations": [
            "house_vault"
          ]
        },
        {
          "name": "house_vault",
          "writable": true
        }
      ],
      "args": []
    },
    {
      "name": "update_config",
      "discriminator": [
        29,
        158,
        252,
        191,
        10,
        83,
        219,
        99
      ],
      "accounts": [
        {
          "name": "admin",
          "writable": true,
          "signer": true,
          "relations": [
            "config"
          ]
        },
        {
          "name": "config",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  103,
                  97,
                  109,
                  101,
                  95,
                  99,
                  111,
                  110,
                  102,
                  105,
                  103
                ]
              }
            ]
          }
        }
      ],
      "args": [
        {
          "name": "params",
          "type": {
            "defined": {
              "name": "UpdateConfigParams"
            }
          }
        }
      ]
    },
    {
      "name": "withdraw_house",
      "discriminator": [
        226,
        236,
        222,
        156,
        198,
        230,
        70,
        147
      ],
      "accounts": [
        {
          "name": "house_authority",
          "writable": true,
          "signer": true,
          "relations": [
            "house_vault"
          ]
        },
        {
          "name": "house_vault",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  104,
                  111,
                  117,
                  115,
                  101,
                  95,
                  118,
                  97,
                  117,
                  108,
                  116
                ]
              },
              {
                "kind": "account",
                "path": "house_authority"
              }
            ]
          }
        }
      ],
      "args": [
        {
          "name": "amount",
          "type": "u64"
        }
      ]
    }
  ],
  "accounts": [
    {
      "name": "GameConfig",
      "discriminator": [
        45,
        146,
        146,
        33,
        170,
        69,
        96,
        133
      ]
    },
    {
      "name": "GameSession",
      "discriminator": [
        150,
        116,
        20,
        197,
        205,
        121,
        220,
        240
      ]
    },
    {
      "name": "HouseVault",
      "discriminator": [
        125,
        17,
        104,
        101,
        16,
        34,
        39,
        135
      ]
    }
  ],
  "events": [
    {
      "name": "InitializeHouseVaultEvent",
      "discriminator": [
        168,
        177,
        147,
        20,
        101,
        83,
        103,
        28
      ]
    },
    {
      "name": "RoundPlayedEvent",
      "discriminator": [
        254,
        181,
        20,
        116,
        246,
        74,
        159,
        248
      ]
    },
    {
      "name": "SessionCashedOutEvent",
      "discriminator": [
        195,
        76,
        152,
        45,
        138,
        65,
        41,
        62
      ]
    },
    {
      "name": "SessionCleanedEvent",
      "discriminator": [
        237,
        15,
        33,
        222,
        164,
        153,
        148,
        218
      ]
    },
    {
      "name": "SessionLostEvent",
      "discriminator": [
        195,
        211,
        168,
        54,
        137,
        90,
        214,
        163
      ]
    },
    {
      "name": "SessionStartedEvent",
      "discriminator": [
        94,
        226,
        93,
        23,
        167,
        17,
        206,
        191
      ]
    },
    {
      "name": "ToggleHouseLockEvent",
      "discriminator": [
        125,
        201,
        183,
        134,
        233,
        188,
        245,
        108
      ]
    }
  ],
  "errors": [
    {
      "code": 6000,
      "name": "HouseLocked",
      "msg": "House vault is locked"
    },
    {
      "code": 6001,
      "name": "InvalidSessionStatus",
      "msg": "Session is not active"
    },
    {
      "code": 6002,
      "name": "InvalidBetAmount",
      "msg": "Bet amount must be greater than zero"
    },
    {
      "code": 6003,
      "name": "RoundMismatch",
      "msg": "Round number mismatch"
    },
    {
      "code": 6004,
      "name": "TreasureInvalid",
      "msg": "Treasure amount invalid or exceeds max payout"
    },
    {
      "code": 6005,
      "name": "InsufficientVaultBalance",
      "msg": "Insufficient vault balance for payout"
    },
    {
      "code": 6006,
      "name": "Overflow",
      "msg": "Arithmetic overflow"
    },
    {
      "code": 6007,
      "name": "InsufficientTreasure",
      "msg": "Cannot cash out with treasure less than or equal to bet"
    },
    {
      "code": 6008,
      "name": "InvalidConfig",
      "msg": "Invalid game configuration"
    },
    {
      "code": 6009,
      "name": "MaxDivesReached",
      "msg": "Maximum number of dives reached"
    },
    {
      "code": 6010,
      "name": "InvalidSlotHash",
      "msg": "Could not retrieve valid slot hash from SlotHashes sysvar"
    },
    {
      "code": 6011,
      "name": "SessionNotExpired",
      "msg": "Session has not expired yet - cannot clean up"
    },
    {
      "code": 6012,
      "name": "VaultHasReservedFunds",
      "msg": "Cannot reset vault reserved when total_reserved > 0 - may have active sessions"
    },
    {
      "code": 6013,
      "name": "VaultCapacityExceeded",
      "msg": "Vault capacity exceeded - too many concurrent sessions would risk insolvency"
    }
  ],
  "types": [
    {
      "name": "GameConfig",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "admin",
            "type": "pubkey"
          },
          {
            "name": "base_survival_ppm",
            "type": "u32"
          },
          {
            "name": "decay_per_dive_ppm",
            "type": "u32"
          },
          {
            "name": "min_survival_ppm",
            "type": "u32"
          },
          {
            "name": "treasure_multiplier_num",
            "type": "u16"
          },
          {
            "name": "treasure_multiplier_den",
            "type": "u16"
          },
          {
            "name": "max_payout_multiplier",
            "type": "u16"
          },
          {
            "name": "max_dives",
            "type": "u16"
          },
          {
            "name": "fixed_bet",
            "type": "u64"
          },
          {
            "name": "bump",
            "type": "u8"
          }
        ]
      }
    },
    {
      "name": "GameConfigParams",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "base_survival_ppm",
            "type": {
              "option": "u32"
            }
          },
          {
            "name": "decay_per_dive_ppm",
            "type": {
              "option": "u32"
            }
          },
          {
            "name": "min_survival_ppm",
            "type": {
              "option": "u32"
            }
          },
          {
            "name": "treasure_multiplier_num",
            "type": {
              "option": "u16"
            }
          },
          {
            "name": "treasure_multiplier_den",
            "type": {
              "option": "u16"
            }
          },
          {
            "name": "max_payout_multiplier",
            "type": {
              "option": "u16"
            }
          },
          {
            "name": "max_dives",
            "type": {
              "option": "u16"
            }
          },
          {
            "name": "fixed_bet",
            "type": {
              "option": "u64"
            }
          }
        ]
      }
    },
    {
      "name": "GameSession",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "user",
            "type": "pubkey"
          },
          {
            "name": "house_vault",
            "type": "pubkey"
          },
          {
            "name": "status",
            "type": {
              "defined": {
                "name": "SessionStatus"
              }
            }
          },
          {
            "name": "bet_amount",
            "type": "u64"
          },
          {
            "name": "current_treasure",
            "type": "u64"
          },
          {
            "name": "max_payout",
            "type": "u64"
          },
          {
            "name": "dive_number",
            "type": "u16"
          },
          {
            "name": "bump",
            "type": "u8"
          },
          {
            "name": "last_active_slot",
            "docs": [
              "Phase 2: Activity tracking for timeout-based cleanup",
              "Slot number when session was last active",
              "Updated on: start_session, play_round (if survived), cash_out"
            ],
            "type": "u64"
          }
        ]
      }
    },
    {
      "name": "HouseVault",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "house_authority",
            "type": "pubkey"
          },
          {
            "name": "game_keeper",
            "type": "pubkey"
          },
          {
            "name": "locked",
            "type": "bool"
          },
          {
            "name": "total_reserved",
            "type": "u64"
          },
          {
            "name": "bump",
            "type": "u8"
          }
        ]
      }
    },
    {
      "name": "InitializeHouseVaultEvent",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "house_vault",
            "type": "pubkey"
          },
          {
            "name": "house_authority",
            "type": "pubkey"
          },
          {
            "name": "locked",
            "type": "bool"
          },
          {
            "name": "timestamp",
            "type": "i64"
          }
        ]
      }
    },
    {
      "name": "RoundPlayedEvent",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "session",
            "type": "pubkey"
          },
          {
            "name": "user",
            "type": "pubkey"
          },
          {
            "name": "dive_number",
            "type": "u16"
          },
          {
            "name": "current_treasure",
            "type": "u64"
          },
          {
            "name": "timestamp",
            "type": "i64"
          }
        ]
      }
    },
    {
      "name": "SessionCashedOutEvent",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "session",
            "type": "pubkey"
          },
          {
            "name": "user",
            "type": "pubkey"
          },
          {
            "name": "house_vault",
            "type": "pubkey"
          },
          {
            "name": "payout_amount",
            "type": "u64"
          },
          {
            "name": "final_dive_number",
            "type": "u16"
          },
          {
            "name": "timestamp",
            "type": "i64"
          }
        ]
      }
    },
    {
      "name": "SessionCleanedEvent",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "session",
            "type": "pubkey"
          },
          {
            "name": "user",
            "type": "pubkey"
          },
          {
            "name": "crank",
            "type": "pubkey"
          },
          {
            "name": "released_amount",
            "type": "u64"
          },
          {
            "name": "slots_inactive",
            "type": "u64"
          }
        ]
      }
    },
    {
      "name": "SessionLostEvent",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "session",
            "type": "pubkey"
          },
          {
            "name": "user",
            "type": "pubkey"
          },
          {
            "name": "house_vault",
            "type": "pubkey"
          },
          {
            "name": "bet_amount",
            "type": "u64"
          },
          {
            "name": "final_dive_number",
            "type": "u16"
          },
          {
            "name": "timestamp",
            "type": "i64"
          }
        ]
      }
    },
    {
      "name": "SessionStartedEvent",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "session",
            "type": "pubkey"
          },
          {
            "name": "user",
            "type": "pubkey"
          },
          {
            "name": "house_vault",
            "type": "pubkey"
          },
          {
            "name": "bet_amount",
            "type": "u64"
          },
          {
            "name": "max_payout",
            "type": "u64"
          },
          {
            "name": "timestamp",
            "type": "i64"
          }
        ]
      }
    },
    {
      "name": "SessionStatus",
      "type": {
        "kind": "enum",
        "variants": [
          {
            "name": "Active"
          },
          {
            "name": "Lost"
          },
          {
            "name": "CashedOut"
          }
        ]
      }
    },
    {
      "name": "ToggleHouseLockEvent",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "house_vault",
            "type": "pubkey"
          },
          {
            "name": "house_authority",
            "type": "pubkey"
          },
          {
            "name": "locked",
            "type": "bool"
          },
          {
            "name": "timestamp",
            "type": "i64"
          }
        ]
      }
    },
    {
      "name": "UpdateConfigParams",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "base_survival_ppm",
            "type": {
              "option": "u32"
            }
          },
          {
            "name": "decay_per_dive_ppm",
            "type": {
              "option": "u32"
            }
          },
          {
            "name": "min_survival_ppm",
            "type": {
              "option": "u32"
            }
          },
          {
            "name": "treasure_multiplier_num",
            "type": {
              "option": "u16"
            }
          },
          {
            "name": "treasure_multiplier_den",
            "type": {
              "option": "u16"
            }
          },
          {
            "name": "max_payout_multiplier",
            "type": {
              "option": "u16"
            }
          },
          {
            "name": "max_dives",
            "type": {
              "option": "u16"
            }
          },
          {
            "name": "fixed_bet",
            "type": {
              "option": "u64"
            }
          }
        ]
      }
    }
  ]
};
