/**
 * AUTO-GENERATED Solana Account Data Parsers
 *
 * Generated from: anchor_project/the_fool/programs/dive_game/src/states.rs
 * DO NOT EDIT THIS FILE MANUALLY - Run 'npm run generate-parsers' instead
 *
 * This ensures frontend parsers always match on-chain account layouts.
 */

import { PublicKey } from "@solana/web3.js";
import BN from "bn.js";

/**
 * SessionStatus enum - matches contract
 * AUTO-GENERATED - DO NOT EDIT MANUALLY
 */
export type SessionStatus = "Active" | "Lost" | "CashedOut";

export function parseSessionStatus(variant: number): SessionStatus {
  switch (variant) {
    case 0:
      return "Active";
    case 1:
      return "Lost";
    case 2:
      return "CashedOut";
    default:
      throw new Error(`Unknown SessionStatus variant: ${variant}`);
  }
}

export function SessionStatusToVariant(status: SessionStatus): number {
  switch (status) {
    case "Active":
      return 0;
    case "Lost":
      return 1;
    case "CashedOut":
      return 2;
    default:
      throw new Error(`Unknown SessionStatus: ${status}`);
  }
}

/**
 * HouseVault account data
 * Matches: pub struct HouseVault in states.rs
 * AUTO-GENERATED - DO NOT EDIT MANUALLY
 */
export interface HouseVaultAccount {
  houseAuthority: PublicKey; // Cold wallet (can withdraw/change config)
  gameKeeper: PublicKey; // Hot wallet (signs play_round for server RNG)
  locked: boolean;
  totalReserved: BN;
  bump: number;
}

/**
 * Parse HouseVault account data
 * AUTO-GENERATED - DO NOT EDIT MANUALLY
 *
 * Layout:
 * - [0..8]    discriminator (8 bytes)
 * - [8..40]    house_authority (Pubkey, 32 bytes)
 * - [40..72]   game_keeper (Pubkey, 32 bytes)
 * - [72..73]   locked (bool, 1 byte)
 * - [73..81]   total_reserved (u64, 8 bytes)
 * - [81..82]   bump (u8, 1 byte)
 */
export function parseHouseVaultData(
  dataInput: Uint8Array | Buffer
): HouseVaultAccount {
  const data = Buffer.from(dataInput);
  let offset = 8; // skip discriminator

  const houseAuthority = new PublicKey(data.slice(offset, offset + 32));
  offset += 32;

  const gameKeeper = new PublicKey(data.slice(offset, offset + 32));
  offset += 32;

  const locked = data.readUInt8(offset) === 1;
  offset += 1;

  const totalReserved = new BN(data.slice(offset, offset + 8), "le");
  offset += 8;

  const bump = data.readUInt8(offset);
  offset += 1;

  return {
    houseAuthority,
    gameKeeper,
    locked,
    totalReserved,
    bump,
  };
}

/**
 * GameConfig account data
 * Matches: pub struct GameConfig in states.rs
 * AUTO-GENERATED - DO NOT EDIT MANUALLY
 */
export interface GameConfigAccount {
  admin: PublicKey;
  baseSurvivalPpm: number;
  decayPerDivePpm: number;
  minSurvivalPpm: number;
  treasureMultiplierNum: number;
  treasureMultiplierDen: number;
  maxPayoutMultiplier: number;
  maxDives: number;
  minBet: BN;
  maxBet: BN;
  bump: number;
}

/**
 * Parse GameConfig account data
 * AUTO-GENERATED - DO NOT EDIT MANUALLY
 *
 * Layout:
 * - [0..8]    discriminator (8 bytes)
 * - [8..40]    admin (Pubkey, 32 bytes)
 * - [40..44]   base_survival_ppm (u32, 4 bytes)
 * - [44..48]   decay_per_dive_ppm (u32, 4 bytes)
 * - [48..52]   min_survival_ppm (u32, 4 bytes)
 * - [52..54]   treasure_multiplier_num (u16, 2 bytes)
 * - [54..56]   treasure_multiplier_den (u16, 2 bytes)
 * - [56..58]   max_payout_multiplier (u16, 2 bytes)
 * - [58..60]   max_dives (u16, 2 bytes)
 * - [60..68]   min_bet (u64, 8 bytes)
 * - [68..76]   max_bet (u64, 8 bytes)
 * - [76..77]   bump (u8, 1 byte)
 */
export function parseGameConfigData(
  dataInput: Uint8Array | Buffer
): GameConfigAccount {
  const data = Buffer.from(dataInput);
  let offset = 8; // skip discriminator

  const admin = new PublicKey(data.slice(offset, offset + 32));
  offset += 32;

  const baseSurvivalPpm = data.readUInt32LE(offset);
  offset += 4;

  const decayPerDivePpm = data.readUInt32LE(offset);
  offset += 4;

  const minSurvivalPpm = data.readUInt32LE(offset);
  offset += 4;

  const treasureMultiplierNum = data.readUInt16LE(offset);
  offset += 2;

  const treasureMultiplierDen = data.readUInt16LE(offset);
  offset += 2;

  const maxPayoutMultiplier = data.readUInt16LE(offset);
  offset += 2;

  const maxDives = data.readUInt16LE(offset);
  offset += 2;

  const minBet = new BN(data.slice(offset, offset + 8), "le");
  offset += 8;

  const maxBet = new BN(data.slice(offset, offset + 8), "le");
  offset += 8;

  const bump = data.readUInt8(offset);
  offset += 1;

  return {
    admin,
    baseSurvivalPpm,
    decayPerDivePpm,
    minSurvivalPpm,
    treasureMultiplierNum,
    treasureMultiplierDen,
    maxPayoutMultiplier,
    maxDives,
    minBet,
    maxBet,
    bump,
  };
}

/**
 * GameSession account data
 * Matches: pub struct GameSession in states.rs
 * AUTO-GENERATED - DO NOT EDIT MANUALLY
 */
export interface GameSessionAccount {
  user: PublicKey;
  houseVault: PublicKey;
  status: SessionStatus;
  betAmount: BN;
  currentTreasure: BN;
  maxPayout: BN;
  diveNumber: number;
  bump: number; // NOTE: rng_seed removed in Phase 1 RNG security enhancement
  lastActiveSlot: BN;
}

/**
 * Parse GameSession account data
 * AUTO-GENERATED - DO NOT EDIT MANUALLY
 *
 * Layout:
 * - [0..8]    discriminator (8 bytes)
 * - [8..40]    user (Pubkey, 32 bytes)
 * - [40..72]   house_vault (Pubkey, 32 bytes)
 * - [72..73]   status (SessionStatus, 1 byte)
 * - [73..81]   bet_amount (u64, 8 bytes)
 * - [81..89]   current_treasure (u64, 8 bytes)
 * - [89..97]   max_payout (u64, 8 bytes)
 * - [97..99]   dive_number (u16, 2 bytes)
 * - [99..100]  bump (u8, 1 byte)
 * - [100..108] last_active_slot (u64, 8 bytes)
 */
export function parseGameSessionData(
  dataInput: Uint8Array | Buffer
): GameSessionAccount {
  const data = Buffer.from(dataInput);
  let offset = 8; // skip discriminator

  const user = new PublicKey(data.slice(offset, offset + 32));
  offset += 32;

  const houseVault = new PublicKey(data.slice(offset, offset + 32));
  offset += 32;

  const status = parseSessionStatus(data.readUInt8(offset));
  offset += 1;

  const betAmount = new BN(data.slice(offset, offset + 8), "le");
  offset += 8;

  const currentTreasure = new BN(data.slice(offset, offset + 8), "le");
  offset += 8;

  const maxPayout = new BN(data.slice(offset, offset + 8), "le");
  offset += 8;

  const diveNumber = data.readUInt16LE(offset);
  offset += 2;

  const bump = data.readUInt8(offset);
  offset += 1;

  const lastActiveSlot = new BN(data.slice(offset, offset + 8), "le");
  offset += 8;

  return {
    user,
    houseVault,
    status,
    betAmount,
    currentTreasure,
    maxPayout,
    diveNumber,
    bump,
    lastActiveSlot,
  };
}
