#!/bin/bash

# Sync IDL Script
# Copies the generated IDL from anchor build to the frontend
# and regenerates TypeScript types

set -e  # Exit on error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${BLUE}🔄 Syncing IDL from Anchor to Frontend...${NC}\n"

# Define paths
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ANCHOR_DIR="$PROJECT_ROOT/anchor_project/the_fool"
FRONTEND_DIR="$PROJECT_ROOT/frontend/the_fool"
ANCHOR_IDL="$ANCHOR_DIR/target/idl/dive_game.json"
FRONTEND_IDL_DIR="$FRONTEND_DIR/lib/solana/idl"
FRONTEND_IDL_JSON="$FRONTEND_IDL_DIR/dive_game.json"
FRONTEND_IDL_TS="$FRONTEND_IDL_DIR/dive_game.ts"

echo "📁 Project root: $PROJECT_ROOT"
echo "⚓ Anchor project: $ANCHOR_DIR"
echo "🎨 Frontend project: $FRONTEND_DIR"
echo ""

# Step 1: Check if anchor IDL exists
if [ ! -f "$ANCHOR_IDL" ]; then
    echo -e "${RED}❌ Error: Anchor IDL not found at $ANCHOR_IDL${NC}"
    echo -e "${YELLOW}💡 Run 'anchor build' first to generate the IDL${NC}"
    exit 1
fi

echo -e "${GREEN}✅ Found Anchor IDL${NC}"

# Step 2: Create frontend IDL directory if it doesn't exist
mkdir -p "$FRONTEND_IDL_DIR"

# Step 3: Check if IDLs are already in sync
if [ -f "$FRONTEND_IDL_JSON" ]; then
    if cmp -s "$ANCHOR_IDL" "$FRONTEND_IDL_JSON"; then
        echo -e "${GREEN}✅ IDL already in sync, no changes needed${NC}"
        exit 0
    else
        echo -e "${YELLOW}⚠️  IDL out of sync, updating...${NC}"
    fi
else
    echo -e "${YELLOW}⚠️  Frontend IDL doesn't exist, creating...${NC}"
fi

# Step 4: Copy JSON IDL
echo -e "${BLUE}📋 Copying dive_game.json...${NC}"
cp "$ANCHOR_IDL" "$FRONTEND_IDL_JSON"
echo -e "${GREEN}✅ Copied JSON IDL${NC}"

# Step 5: Extract program ID from IDL
PROGRAM_ID=$(jq -r '.address' "$ANCHOR_IDL")
echo -e "${BLUE}🔑 Program ID: $PROGRAM_ID${NC}"

# Step 6: Generate TypeScript types
echo -e "${BLUE}🔨 Generating TypeScript types...${NC}"

# Check if we're in the frontend directory, if not cd to it
cd "$FRONTEND_DIR"

# Use npx to run the IDL type generator (comes with @coral-xyz/anchor)
npx @coral-xyz/anchor idl convert \
    "$FRONTEND_IDL_JSON" \
    --out-ts "$FRONTEND_IDL_TS" \
    2>/dev/null || {
    
    # Fallback: Manual TypeScript generation
    echo -e "${YELLOW}⚠️  anchor idl convert not available, using fallback...${NC}"
    
    cat > "$FRONTEND_IDL_TS" << 'TYPESCRIPT_TEMPLATE'
/**
 * Program IDL in camelCase format in order to be used in JS/TS.
 *
 * Note that this is only a type helper and is not the actual IDL. The original
 * IDL can be found at `target/idl/dive_game.json`.
 * 
 * AUTO-GENERATED - DO NOT EDIT MANUALLY
 * Generated by scripts/sync-idl.sh
 */

import type { Program } from '@coral-xyz/anchor';
import type { PublicKey } from '@solana/web3.js';

TYPESCRIPT_TEMPLATE

    # Add the actual type export by parsing the JSON
    node -e "
    const fs = require('fs');
    const idl = JSON.parse(fs.readFileSync('$FRONTEND_IDL_JSON', 'utf8'));
    
    // Simple conversion - just export the IDL type
    console.log('export type DiveGame = ' + JSON.stringify(idl, null, 2) + ';');
    console.log('');
    console.log('export const IDL: DiveGame = ' + JSON.stringify(idl, null, 2) + ';');
    " >> "$FRONTEND_IDL_TS"
}

echo -e "${GREEN}✅ Generated TypeScript types${NC}"

# Step 7: Update program ID in .env.local if different
ENV_FILE="$FRONTEND_DIR/.env.local"
if [ -f "$ENV_FILE" ]; then
    CURRENT_PROGRAM_ID=$(grep "NEXT_PUBLIC_PROGRAM_ID" "$ENV_FILE" | cut -d '=' -f2 | tr -d '"' | tr -d ' ')
    
    if [ "$CURRENT_PROGRAM_ID" != "$PROGRAM_ID" ]; then
        echo -e "${YELLOW}⚠️  Program ID mismatch in .env.local${NC}"
        echo -e "${YELLOW}   Current: $CURRENT_PROGRAM_ID${NC}"
        echo -e "${YELLOW}   New: $PROGRAM_ID${NC}"
        echo -e "${BLUE}💡 Update .env.local manually or run:${NC}"
        echo -e "   sed -i '' 's/NEXT_PUBLIC_PROGRAM_ID=.*/NEXT_PUBLIC_PROGRAM_ID=$PROGRAM_ID/' $ENV_FILE"
    else
        echo -e "${GREEN}✅ Program ID matches .env.local${NC}"
    fi
fi

# Step 8: Format the generated TypeScript file
echo -e "${BLUE}🎨 Formatting TypeScript file...${NC}"
if command -v prettier &> /dev/null; then
    prettier --write "$FRONTEND_IDL_TS" > /dev/null 2>&1 || true
    echo -e "${GREEN}✅ Formatted with Prettier${NC}"
else
    echo -e "${YELLOW}⚠️  Prettier not found, skipping formatting${NC}"
fi

# Step 9: Update discriminators in solanaHelpers.ts (preserve manual exports!)
echo -e "${BLUE}🔨 Updating instruction discriminators...${NC}"
SOLANA_HELPERS="$FRONTEND_DIR/lib/ports/solanaHelpers.ts"

if [ -f "$SOLANA_HELPERS" ]; then
    # Extract discriminators from IDL and format them
    DISCRIMINATORS=$(node -e "
    const fs = require('fs');
    const idl = JSON.parse(fs.readFileSync('$FRONTEND_IDL_JSON', 'utf8'));
    
    const instructions = idl.instructions || [];
    const discMap = {};
    
    instructions.forEach(inst => {
        const name = inst.name.toUpperCase().replace(/_/g, '_');
        const disc = inst.discriminator || [];
        discMap[name] = disc;
    });
    
    console.log(JSON.stringify(discMap, null, 2));
    ")
    
    # Create a temp file with updated discriminators
    node -e "
    const fs = require('fs');
    const discMap = $DISCRIMINATORS;
    
    let content = fs.readFileSync('$SOLANA_HELPERS', 'utf8');
    
    // Build the new discriminators object
    let newDisc = \`/**
 * Instruction discriminators from IDL
 * These are generated by Anchor and MUST match exactly
 * Generated from target/idl/dive_game.json
 * Last synced: $(date)
 */
export const DISCRIMINATORS = {\`;
    
    for (const [name, disc] of Object.entries(discMap)) {
        newDisc += \`\n  \${name}: Buffer.from([\${disc.join(', ')}]),\`;
    }
    newDisc += '\n};';
    
    // Replace the DISCRIMINATORS section
    const regex = /\/\*\*[^]*?Instruction discriminators[^]*?\*\/\s*export const DISCRIMINATORS = \{[^}]*\};/;
    if (regex.test(content)) {
        content = content.replace(regex, newDisc);
        
        // CRITICAL: Check if file has manual exports section
        // If not, add it at the end
        const manualExportsMarker = '// Re-exports and Wrappers (Added manually - do not remove!)';
        if (!content.includes(manualExportsMarker)) {
            console.log('⚠️  Manual exports section missing, adding it back...');
            
            // Append the manual exports section
            content += \`

// ============================================================================
// Re-exports and Wrappers (Added manually - do not remove!)
// ============================================================================

import {
  getGameConfigAddress,
  getHouseVaultAddress,
  getSessionAddress,
} from \"../solana/pdas\";
import { lamportsToSol, solToLamports } from \"../utils/lamports\";

// Program ID from environment
export const PROGRAM_ID = new PublicKey(
  process.env.NEXT_PUBLIC_PROGRAM_ID ||
    \"9GxDuBwkkzJWe7ij6xrYv5FFAuqkDW5hjtripZAJgKb7\"
);

// PDA helper wrappers that return just the address (not tuple)
export function getConfigPDA(): PublicKey {
  const [pda] = getGameConfigAddress(PROGRAM_ID);
  return pda;
}

export function getHouseVaultPDA(houseAuthority: PublicKey): PublicKey {
  const [pda] = getHouseVaultAddress(houseAuthority, PROGRAM_ID);
  return pda;
}

export function getSessionPDA(
  user: PublicKey,
  sessionIndex: bigint | number
): PublicKey {
  const [pda] = getSessionAddress(user, sessionIndex, PROGRAM_ID);
  return pda;
}

// Export lamport utilities
export { lamportsToSol, solToLamports };
\`;
        }
        
        fs.writeFileSync('$SOLANA_HELPERS', content);
        console.log('✅ Updated discriminators and preserved manual exports');
    } else {
        console.log('⚠️  Could not find DISCRIMINATORS section');
    }
    "
    
    echo -e "${GREEN}✅ Updated instruction discriminators${NC}"
else
    echo -e "${YELLOW}⚠️  solanaHelpers.ts not found, skipping discriminator update${NC}"
fi

# Step 10: Summary
echo ""
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}✨ IDL Sync Complete!${NC}"
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "${BLUE}📦 Files Updated:${NC}"
echo "   ✅ $FRONTEND_IDL_JSON"
echo "   ✅ $FRONTEND_IDL_TS"
echo "   ✅ $SOLANA_HELPERS (discriminators)"
echo ""
echo -e "${BLUE}🔑 Program ID:${NC} $PROGRAM_ID"
echo ""
echo -e "${YELLOW}💡 Next Steps:${NC}"
echo "   1. Verify types in your IDE"
echo "   2. Run 'npm run build' in frontend to check for type errors"
echo "   3. Test transaction building with updated discriminators"
echo "   4. Commit the updated IDL files"
echo ""
